# Generated by Django 4.2.2 on 2023-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher_group_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='phone_number'),
        ),
    ]
